{
      "MD033": true
}

{
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 100
  code_blocks: false
  # Include tables
  tables: false
  # Include headings
  headings: true
}
